project_id = "pkrmowguxlphrfbvalzl"

[functions.verify-worker-pin]
verify_jwt = false

[functions.verify-worker-badge]
verify_jwt = false

[functions.verify-worker-session]
verify_jwt = false

[functions.worker-action]
verify_jwt = false

[functions.r2-image]
verify_jwt = false
