ALTER TABLE public.sectors
  ADD COLUMN IF NOT EXISTS rows integer NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS columns integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS levels integer NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS width_cm integer NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS depth_cm integer NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS height_cm integer NOT NULL DEFAULT 180,
  ADD COLUMN IF NOT EXISTS position_x integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS position_y integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS orientation integer NOT NULL DEFAULT 0;